psalm.xml
src/Plugin.php

On a fresh install in a repository that has Laravel installed, I was getting the following error:
```
$ ./vendor/bin/psalm
Scanning files...
In Config.php line 892:
Failed to load plugin Psalm\LaravelPlugin\Plugin  
In Generator.php line 53:
array_merge(): Argument #2 is not an array  
```
Upon further debugging, I was getting this because the `LaravelIdeHelper` service provider wasn't being properly booted up, resulting in that library attempting to use configuration data that did not exist within my `config/` directory.

Resolving an issue in the plugin where it isn't always bootstrapped.

---

composer.json

When writing the versions without the wildcard, you lock it to the x.x.0 tag.
This fixes it by allowing the last to be anything.

Fix specific versions for plugin

---

.github/workflows/psalm.yml

I noticed that this workflow wasn't kicked off when I made a PR introducing changes. I believe this will now kickoff the workflow whenever someone makes a PR

chore: run github workflow on pr

---

src/AbstractPlugin.php
src/ReturnTypeProvider/RedirectReturnTypeProvider.php

👋 First time user of psalm, and therefore my first time contributing an extension. Totally welcome to critique and feedback if I am doing something wrong.
It's my understanding that I should be returning a `UnionType`, even though the _actual_ type isn't a `Union`, [per the docs](https://psalm.dev/docs/running_psalm/plugins/plugins_type_system/) 
> All type Psalm's type information you are likely to use will be wrapped in a Union Type.
-------
[Here are the laravel docs](https://laravel.com/docs/7.x/helpers#method-redirect) describing this dynamic return type
> The redirect function returns a redirect HTTP response, or returns the redirector instance if called with no arguments:

feature: redirect return types

---

src/Stubs/Enumerable.stubphp

When i was testing with a 5.5 app of mine, I ran into
```
MissingDependency - app/Tax/TaxService.php:442:20 - Illuminate\Database\Eloquent\Collection depends on class or interface illuminate\support\enumerable that does not exist (see https://psalm.dev/157)
$profile = $user->billingProfiles()->find($paymentDetails['billingProfileId']);
```
That is because the enumerable interface was added in laravel 6.
This stub fixes that issue, and https://github.com/psalm/psalm-plugin-laravel/issues/37 would have caught it sooner

fix: stub out enumerable since it doesnt exist in 5.5

---

src/FakeMetaCommand.php

https://github.com/psalm/psalm-plugin-laravel/issues/24#issuecomment-611184388 explains this pretty well, in conjunction with my comment.
Essentially the existing implementation makes it so that nothing else executed after it can call `class_exists`, even the application source code being tested

Fix: we should be able to call class_exists

---

.gitignore
src/Plugin.php

I believe this should be a simple solution for https://github.com/psalm/psalm-plugin-laravel/issues/43 , since phpstorm won't treat files ending in `.stubphp` as php files, but psalm will still interpret them as stubs

change file extension of ide helper files so phpstorm doesnt analyze them

---

.github/workflows/test.yml
composer.json
psalm.xml

- More specific dependencies that we actually rely on (or will soon as we add full Laravel support)
- A test matrix for testing various versions

[wip] Cleanup dependencies

---

.github/workflows/test.yml
composer.json

After going through dependency hell, i believe laravel 5.8 is the minimum composer can resolve packages for. Let's see if tests get green

chore: update dependencies to actual minimum requirements

---

src/Plugin.php
src/ReturnTypeProvider/UrlReturnTypeProvider.php
tests/acceptance/UrlReturnType.feature

`url` returns an instance of url generator with no params, otherwise returns a string

feature: add return type info for url helper

---

composer.json
src/Plugin.php
tests/acceptance/ExceptionHandler.feature

Related: https://github.com/vimeo/psalm/issues/3243
This bootstrapper was replacing the php exception handler, causing psalm to then have status codes of 0 on failures.
This isn't full regression test, but it's at least a start: https://github.com/weirdan/codeception-psalm-module/issues/9

fix: keep psalm exception handler

---

src/PropertyProvider/ModelPropertyProvider.php
src/Stubs/MorphMany.stubphp
src/Stubs/MorphOneOrMany.stubphp
tests/Models/Comment.php
tests/Models/Video.php
tests/acceptance/EloquentRelationTypes.feature

Basic support for polymorphic relations, should close #80 cc @brendt
It isn't smart enough to figure out `MorphTo` models, I'm just leaving that as mixed for now. Feel free to pr that functionality!

feature: support for polymorphic relations

---

composer.json

See issue: https://github.com/psalm/psalm-plugin-laravel/issues/89 for more details
Note: This is temporary solution to fix the issue until Laravel-ide-helper release a new version so we can tag the version in the composer requirements after

fixing conflict issue in composer requirements

---

src/FakeModelsCommand.php

This PR fixes #98 . 
The empty `getPropertiesFromMethods` method is clearly a bug, since it adds crucial information to the ide helper models file.
By removing it, the original implementation is used again, and that works fine. I've tested this in our own Laravel project, and it fixes the issue described in #98.

Remove unused getPropertiesFromMethods method

---

.github/workflows/test.yml

following along with https://github.com/laravel/framework/pull/33158

chore: test with composer 2

---

src/Stubs/BelongsToMany.stubphp
tests/acceptance/EloquentRelationTypes.feature

This PR fixes #116.
Added correct return anotation for the `first` method of BelongsToMany relationship. Added test. Also I removed unessesary code in stub file.

Fix anotation for first method of BelongsToMany

---

src/Stubs/EloquentBuilder.stubphp

Here's an example. Should be easier than explaining. 
Here's the issue:
https://psalm.dev/r/6c65f643a1
Here's the fix:
https://psalm.dev/r/ffc832b680

Make the Model template on the Builder covariant.

---

composer.json

This avoids a BC break in `barryvdh/laravel-ide-helper` 2.9.2, which changed the visibility of several methods from `protected` to `public`.

Prevent installation of `barryvdh/laravel-ide-helper` 2.9.2 and later

---

src/Plugin.php

Close https://github.com/psalm/psalm-plugin-laravel/issues/140
In some cases, psalm-plugin-laravel will stop psalm parsing if a error occurs.
I've addressed this issue by using try/catch to early return.
```
sample$ ./vendor/bin/psalm --no-cache
Scanning files...
Psalm\Exception\ConfigException
Failed to load plugin Psalm\LaravelPlugin\Plugin
at vendor/vimeo/psalm/src/Psalm/Config.php:1158
1154▕                  */
1155▕                 $plugin_object = new $plugin_class_name;
1156▕                 $plugin_object($socket, $plugin_config);
1157▕             } catch (\Throwable $e) {
➜ 1158▕                 throw new ConfigException('Failed to load plugin ' . $plugin_class_name, 0, $e);
1159▕             }
1160▕
1161▕             $project_analyzer->progress->debug('Loaded plugin ' . …
```

Added support for not stopping the execution of psalm even when a error occurs.

---

composer.json
src/FakeModelsCommand.php

LaravelIdeHelper changed the visibility of `getPropertiesFromTable` from `protected` to `public` in this PR: https://github.com/barryvdh/laravel-ide-helper/pull/945
This causes Psalm to fail with the lastest version

Update method signature for getPropertiesFromTable

---

composer.json
src/FakeModelsCommand.php

Reverts psalm/psalm-plugin-laravel#136
I did not realize that ide-helper removed support for laravel 7. I would prefer to keep support for laravel 7 until it has reached end of life.

Revert "Update method signature for getPropertiesFromTable"

---

.github/workflows/lint.yml

Fixes the PHPCS check by running it directly.
This means we're losing the useful check annotations, but PHPCS had been failing with the following error:
```
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2". You are running 7.4.12. in /github/workspace/vendor/composer/platform_check.php on line 24
```
See: https://github.com/psalm/psalm-plugin-laravel/runs/2790324947

fix(lint): run phpcs with php 7.4

---

src/SchemaAggregator.php

This PR will:
- add missing schema declarations taken from `/Illuminate/Database/Schema/Blueprint.php`, Laravel 8
Was not able to find tests checking `if migration with given method usage is found a stub is created with appropriate annotation` - happy to add unit tests if given guidance

Add missing schema declaration

---

stubs/helpers.stubphp
tests/acceptance/Helpers.feature

For me, after upgrading to `psalm-plugin-laravel` 1.4.8, Psalm was no longer able to determine the return type of [`head()`](https://laravel.com/docs/8.x/helpers#method-head), so I'm adding a test case to see if it's just me (unfortunately I wasn't able to run the acceptance tests locally: #165).
**edit**: It is actually not only broken for me.

feature: support head() and last()

---

.gitignore

Running the test locally initialises a `/laravel/` folder, but that folder is not ignored by git.

chore(gitignore): add laravel folder

---

composer.json

Extracted from #168:
1. `illuminate/config` is used here:
https://github.com/psalm/psalm-plugin-laravel/blob/28b697a39aa96986733aae79415bfd776306436f/src/Providers/FacadeStubProvider.php#L6
2. `illuminate/events` is used here:
https://github.com/psalm/psalm-plugin-laravel/blob/28b697a39aa96986733aae79415bfd776306436f/src/Providers/ViewFactoryProvider.php#L31
3. `illuminate/routing` is used here:
https://github.com/psalm/psalm-plugin-laravel/blob/28b697a39aa96986733aae79415bfd776306436f/src/Handlers/Helpers/RedirectHandler.php#L6
4. `illuminate/view` is used here:
https://github.com/psalm/psalm-plugin-laravel/blob/28b697a39aa96986733aae79415bfd776306436f/src/Providers/ViewFactoryProvider.php#L6-L9

fix: add missing illuminate/* dependencies

---

src/Handlers/SuppressHandler.php
src/Plugin.php
tests/acceptance/ConsoleCommand.feature
tests/acceptance/HttpFormRequest.feature
tests/acceptance/Notification.feature

Fixes #144.
Ref: https://laravel.com/docs/8.x/validation#form-request-validation

fix: ignore PropertyNotSetInConstructor in Console\Command, Http\FormRequest and Notifications\Notifications classes

---

src/Providers/ModelStubProvider.php
tests/Models/AbstractUuidModel.php
tests/Models/Secret.php
tests/Models/User.php
tests/acceptance/EloquentModelPropertyTypes.feature

Originally reported in https://github.com/vimeo/psalm/issues/6024.

fix: Support @property on Model with imported type

---

tests/acceptance/Notification.feature

`\Illuminate\Bus\Queuable` has invalid docblock in Laravel 6.0.3 and earlier, which [was fixed in 6.0.4](https://github.com/laravel/framework/commit/35572b39059d64bd2119fbf28638654b2a28ee61).
Therefore we should ignore the new Notification acceptance test in Laravel 6.0.3 and before, using the syntax pointed out [here](https://github.com/psalm/psalm-plugin-laravel/pull/157#issuecomment-877350836).

test(Notification): run only for Laravel 6.0.4+

---

src/Handlers/SuppressHandler.php
tests/laravel-test-baseline.xml
tests/laravel-test-psalm.xml
tests/lumen-test-baseline.xml
tests/lumen-test-psalm.xml

Suppress UnusedClass/PossiblyUnusedMethod on well-known classes/methods of fresh Laravel/Lumen projects

---

stubs/6/EloquentBuilder.stubphp
stubs/6/HasOneOrMany.stubphp
stubs/8/EloquentBuilder.stubphp
stubs/8/HasOneOrMany.stubphp
stubs/EloquentBuilder.stubphp
stubs/HasOneOrMany.stubphp
tests/acceptance/EloquentBuilderTypes.feature
tests/acceptance/EloquentRelationTypes.feature

Fixes #156.
🟢 ~~Includes 🍒 from #181.~~ ~~Blocked by #182.~~

Ensure firstOrNew/Create can be called without parameters in Laravel 8+

---

src/Providers/ModelStubProvider.php

This PR will fix the `database/migrations` path. When the class was extracted in [this commit](https://github.com/psalm/psalm-plugin-laravel/commit/c4c8c0b22af8a7a33035251df89c6e41bbdbc7fb#diff-c6267cd06274097a95b4dc3c1df8988e56cd5cdec71764afc95c1b28fd930d82) it was placed in a nested folder and thus the call to `dirname` needed to be updated to ensure the path is correct.
Thanks 🙌

Fix database migrations path

---

stubs/DBFacade.stubphp
stubs/EloquentBuilder.stubphp
tests/acceptance/DBFacadeAlias.feature
tests/acceptance/EloquentBuilderTypes.feature

Also changed the return type for `DB::raw()`

Added missing Builder methods - count() and whereDate()

---

src/Handlers/Helpers/TransHandler.php

This is needed because this can be a valid translation file:
```php
<?php
return [
'some-string' => 'Abc',
'some-array' => [
'some-value' => 'Def',
'some-other-value' => 'Ghi',
],
];
```
Laravel allows you to do `trans('some-string')` which would return a `string` type or do `trans('some-array')` which will return an `array` type or do `trans('some-array.some-value')` which will return a `string` type, all of which are valid. Therefore the return type should be changed to a `string|array` type.

Updates trans return type to be string or array

---

stubs/Collection.stubphp
tests/acceptance/CollectionTypes.feature

Currently, Psalm cannot infer iterated value type from `\IteratorAggregate<TKey, TValue>`.
see also: https://github.com/vimeo/psalm/issues/7187

feat: support foreach with Support\Collection

---

composer.json

Use `prefer-stable` config in `composer.json` to avoid fragile ci.
https://getcomposer.org/doc/04-schema.md#prefer-stable
- Psalm `dev-master` requires PHP 7.4 https://github.com/vimeo/psalm/blob/cb976f8416b1bb17340996ee25866dd555d5f10f/composer.json#L17
- `"minimum-staility": dev` introduced on #92, but `dev-version` is not required for all of dependencies
<details>
<summary>`composer show` with `"prefer-stable": true`</summary>
```
amphp/amp                                      v2.6.1    A non-blocking concurrency framework for PHP applications.
amphp/byte-stream                              v1.8.1    A stream abstraction to make working with non-blocking I/O simple.
barryvdh/laravel-ide-helper                    v2.9.1    Laravel IDE Helper, generates correct PHPDocs for all Facade …
```

chore: use stable dependencies

---

.github/workflows/test.yml

This PR prevents CI failure caused by unsupported version combinations.
Note:
Test CI stil failing if `--prefer-lowest` flag used with PHP 8.1.
We need bump up `orchestra/testbench` to fix Test CI.
> Added draft support for PHP 8.1.
https://github.com/orchestral/testbench/releases/tag/v6.22.0

chore: test supported PHP version only

---

psalm.xml
src/Providers/ApplicationProvider.php
tests/acceptance/AbortIf.feature
tests/acceptance/CollectionTypes.feature
tests/acceptance/ConsoleCommand.feature
tests/acceptance/Container.feature
tests/acceptance/DBFacadeAlias.feature
tests/acceptance/DatabaseBuilderTypes.feature
tests/acceptance/EloquentBuilderTypes.feature
tests/acceptance/EloquentCollectionTypes.feature
tests/acceptance/EloquentModelPropertyTypes.feature
tests/acceptance/EloquentModelTypes.feature
tests/acceptance/EloquentRelationTypes.feature
tests/acceptance/ExceptionHandler.feature
tests/acceptance/FactoryTypes.feature
tests/acceptance/Helpers.feature
tests/acceptance/HttpFormRequest.feature
tests/acceptance/HttpResourceTypes.feature
tests/acceptance/Notification.feature
tests/acceptance/PathHelpers.feature
tests/acceptance/RedirectReturnType.feature
tests/acceptance/RequestTypes.feature
tests/acceptance/ResponseReturnType.feature
tests/acceptance/UrlReturnType.feature

`totallyTyped` was deprecated in [Psalm v4.21.0](https://github.com/vimeo/psalm/releases/tag/4.21.0).
Drom the [docs](https://psalm.dev/docs/running_psalm/configuration/#totallytyped): `totallyTyped="true"` is equivalent to `errorLevel="1"` and `totallyTyped="false"` is equivalent to `errorLevel="2"` plus `reportMixedIssues="false"`.

Fix Psalm v4.21 compatibility

---

.github/workflows/lint.yml

This fixes the lint action which seemed to have an improperly configured `actions/checkout@v2`.
See #221 for the failing tests. Both PRs should make CI green again.

Fix lint action

---

composer.json
psalm.xml
src/Fakes/FakeMetaCommand.php
src/Fakes/FakeModelsCommand210.php
src/Fakes/FakeModelsCommand291.php
src/Fakes/FakeModelsCommandLogic.php
src/Providers/FakeModelsCommandProvider.php
src/Providers/ModelStubProvider.php
tests/laravel-test-baseline.xml

Prior to this change, projects that used later versions (>=2.10) would have issues with compatibility if it's using this package. This change adds support for later versions of that IDE helper. It builds on a previous PR where the `FakeModelsCommand` class is switched based on the installed version of the later version for compatibility.
I'm sure I missed something so please let me know. :)

Add support for later versions of IDE helper

---

src/Util/ContainerResolver.php

If class require connection to database for creation for example getting state from there and saving to property.
This break psalm anaylis currently. 
This case happen when CI environment does not have connection to database.

Catch even Throwable when trying to create class

---

.github/workflows/lint.yml
src/Providers/ApplicationProvider.php

Use phpcs to auto-fix coding-style issue and push commit to the same branch
Commit example: https://github.com/psalm/psalm-plugin-laravel/pull/258/commits/2e54f1476b24355bcc51053e9d0cd4c70f678db7
Additionally: run action only when sensitive files changed

Automatically fix coding style issues

---

src/Handlers/Eloquent/Schema/SchemaAggregator.php

If you pass `false` into nullable(), for example when turning a column from nullable to non-null, the migration parsing code would ignore this and assume the column was nullable, causing false "potentially null value" errors when the column was used.
This commit adds a check for either no parameter or a true parameter before making the column as nullable.
Fixes psalm/psalm-plugin-laravel#274

Check for a parameter with nullable() in migrations

---

src/Fakes/FakeFilesystem.php
stubs/helpers.stubphp
tests/acceptance/Helpers.feature

Use implementation instead of interface as this implementation is core Laravel functionality, default one, rarely rebinded. Basically to reduce noise and hide architectire issues of Laravel

Make auth()->check() calls readable by Psalm

---

tests/acceptance/Helpers.feature

On Laravel 9.44 AuthManager got @mixin annotations
https://github.com/illuminate/auth/commit/6e61f0393ba1952b82aeeebd86432806dbb0bcfe

Do not run auth() tests on Laravel <9.44

---

psalm-baseline.xml
psalm.xml
src/Fakes/FakeModelsCommand.php
src/Handlers/Application/ContainerHandler.php
src/Handlers/Application/OffsetHandler.php
src/Handlers/Eloquent/Schema/SchemaAggregator.php
src/Handlers/Eloquent/Schema/SchemaColumn.php
src/Handlers/Helpers/PathHandler.php
src/Plugin.php
src/Providers/ApplicationInterfaceProvider.php
src/Providers/ApplicationProvider.php
src/Providers/FacadeStubProvider.php
src/Providers/ModelStubProvider.php
src/Util/ContainerResolver.php
stubs/Database/ManagesTransactions.stub
stubs/EloquentBuilder.stubphp
tests/acceptance/AbortIf.feature
tests/acceptance/EloquentBuilderTypes.feature

Support:
- `lang_path` helper and `Container::langPath()`
- `Database\Connection::transaction()`
- `Eloquent\Builder::chunk()`

Add More stubs: `lang_path`, `Eloquent\Builder::chunk`, `Database\Connection::transaction`

---

stubs/Relation.stubphp
tests/acceptance/EloquentRelationTypes.feature

Fix MorphMany return type when orderBy used

---

composer.json
phpcs.xml
src/Providers/ApplicationProvider.php
tests/Acceptance/acceptance/DatabaseBuilderTypes.feature
tests/Acceptance/acceptance/EloquentBuilderTypes.feature
tests/Acceptance/acceptance/EloquentCollectionTypes.feature
tests/Acceptance/acceptance/EloquentModelPropertyTypes.feature
tests/Acceptance/acceptance/EloquentModelTypes.feature
tests/Acceptance/acceptance/EloquentRelationTypes.feature
tests/Acceptance/acceptance/Helpers.feature
tests/Acceptance/acceptance/HttpResourceTypes.feature
tests/Application/app/Models/AbstractUuidModel.php
tests/Application/app/Models/Car.php
tests/Application/app/Models/Comment.php
tests/Application/app/Models/Image.php
tests/Application/app/Models/Mechanic.php
tests/Application/app/Models/Phone.php
tests/Application/app/Models/Post.php
tests/Application/app/Models/Role.php
tests/Application/app/Models/Secret.php
tests/Application/app/Models/Tag.php
tests/Application/app/Models/User.php
tests/Application/app/Models/Video.php

I've created `Application` dir where we can store not Models only, but also configs, routes - everything we need for testing. It also will have a standard Laravel namespaces that will improve DX.
Why it's important: in next PR I'm going to store somewhere `config/auth.php`, I decided that the default Laravel structure (and default namespaces) will be better for DX.
So, the new [file structure](https://github.com/lptn/psalm-plugin-laravel/tree/application-test-dir/tests) looks like:

Improve DX: Use default Laravel app namespace for Models, create Application dir

---

src/Plugin.php
stubs/9/Foundation/helpers.stubphp
stubs/Collections/helpers.stubphp
stubs/Foundation/helpers.stubphp
stubs/Support/helpers.stubphp
tests/Acceptance/acceptance/CollectionHelpers.feature
tests/Acceptance/acceptance/FoundationHelpers.feature
tests/Acceptance/acceptance/SupportHelpers.feature

Supported new helpers:
- blank
- filled
- transform
- class_basename
- class_uses_recursive
- trait_uses_recursive
- str
- abort_unless
- action
- back
- bcrypt
- broadcast
- dispatch_sync
- event
- data_fill
- data_set
- precognitive
- object_get
+ improved some existing helpers
________
BTW, this is the final bunch of stubs for handlers, it seems like all of them are covered, my favourite one is transform, see  6875b3b :)

Support more helpers (+18 more)

---

src/Providers/ApplicationProvider.php

instantiation should include common parts from artisan.php and public/index.php

Define missing laravel app constants when instantiate Laravel app

---

stubs/Database/Eloquent/Builder.stubphp

Add missing @throws

---

src/Handlers/Eloquent/ModelMethodHandler.php
src/Handlers/Eloquent/ModelPropertyAccessorHandler.php

Fixes:
```
Error: src/Handlers/Eloquent/ModelMethodHandler.php:75:67: ArgumentTypeCoercion: Argument 1 of Psalm\LaravelPlugin\Util\ProxyMethodReturnTypeProvider::executeFakeCall expects Psalm\Internal\Analyzer\StatementsAnalyzer, but parent type Psalm\StatementsSource provided (see https://psalm.dev/193)
```

Fix ArgumentTypeCoercion issue

---

.github/workflows/psalm.yml
.github/workflows/test-laravel.yml
.github/workflows/test.yml

**Changes**
- Run test suite with 8.3, which is released in 2 weeks
- Run psalm action with 8.2 instead of 8.1 (8.1 is skipped in tests.yml)
- Run test when config file has changes

Run test suite with PHP 8.3

---

phpunit.xml

Noticed the phpunit configuration config does not pass validation:
https://github.com/psalm/psalm-plugin-laravel/actions/runs/6826034186/job/18565079257

update phpunit config

---

psalm-baseline.xml
src/Handlers/Eloquent/ModelRelationshipPropertyHandler.php

Closes #386 Undefined array key "factory"
Because HasFactory adds `factory()` method and it also checks for the $factory property, `src/Handlers/Eloquent/ModelRelationshipPropertyHandler.php` treated it as a relationship and thus allowed to use `$factory` no matter declared it or not.

Fix Undefined array key "factory"

---

psalm-baseline.xml
src/Handlers/Auth/AuthHandler.php
tests/Unit/Handlers/Auth/AuthHandlerTest.php

Uncaught Amp\Parallel\Worker\TaskFailureException: UnexpectedValueException thrown in context with message "Cannot get method params for Illuminate\Support\Facades\Auth::user" and code "0" in .../vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Methods.php:484 Stack trace in context:

Fix "Cannot get method params for Illuminate\Support\Facades\Auth::user"

---

src/Providers/CacheDirectoryProvider.php
tests/Unit/Providers/CacheDirectoryProviderTest.php

**Summary**
This PR makes the stub cache directory location configurable via an environment variable `LARAVEL_PLUGIN_CACHE_PATH`.
**Details**
Previously, the path to the cache directory was hardcoded. This change allows overriding the default location by setting the `LARAVEL_PLUGIN_CACHE_PATH` environment variable, which is particularly useful when using Psalm in different CI or Docker environments.
**Example Usage**
```
export LARAVEL_PLUGIN_CACHE_PATH=/tmp/custom-laravel-psalm-cache
./vendor/bin/psalm
```
**or in Dockerfile / CI pipeline:**
```
env:
LARAVEL_PLUGIN_CACHE_PATH: /tmp/cache
```
Closes: #361

fix: make stub cache directory configurable via env
